### PR TITLE
chore(deps): upgrade dependencies

### PR DESCRIPTION
**Pull request by sam-goodwin**
Upgrades project dependencies. See details in [workflow run].

[Workflow Run]: https://github.com/sam-goodwin/typesafe-dynamodb/actions/runs/11376026705

------

*Automatically created by projen via the "upgrade-main" workflow*

### CODE REVIEW

**Comment by msudgh** [comment]
Hi @sam-goodwin, I am seeing a warning about smithy package while using the package. 
Is it good idea to keep it up to date?

>  WARN  deprecated @aws-sdk/smithy-client@3.374.0: This package has moved to @smithy/smithy-client

**Comment by sam-goodwin** [comment]
@msudgh thanks for calling that out! Upgraded the dependencies and switched to `@smithy/smithy-client` here: https://github.com/sam-goodwin/typesafe-dynamodb/pull/64

**Comment by sam-goodwin** [comment]
Going to close this PR in favor of https://github.com/sam-goodwin/typesafe-dynamodb/pull/64. This PR was auto-generated, but #64 also includes the new smithy package.

**Comment by sam-goodwin** [comment]
Should be fixed in v0.8.3

**Pull request closed without merging**
